### ISSUE TITLE
to_excel close

### ISSUE THREAD

**Issue by byersiiasa** [IAMconsortium/pyam#300]
When writing out recently, error on `df.to_excel()`

```
Traceback (most recent call last):

  File "<ipython-input-35-1d4bbdcc4679>", line 1, in <module>
    pdf.to_excel(excel_writer=writer)

  File "C:\Users\byers\AppData\Local\Continuum\anaconda3\envs\EB_Py3_light\lib\site-packages\pyam\core.py", line 1174, in to_excel
    if close:

UnboundLocalError: local variable 'close' referenced before assignment
```

I resolved this in the function by removing the `if`, but not sure if that is safe:

```
#        if close:
        excel_writer.close()
```

**Comment by danielhuppmann** [comment]
I apologise for the inconvenience...
